sync_db:
  npx prisma db push --schema ./src/db/schema.prisma
  sea-orm-cli generate entity \
    --with-serde serialize \
    --model-extra-attributes "typeshare::typeshare" \
    --enum-extra-attributes "typeshare::typeshare" \
    -o src/db/entities