//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::conversation::Entity as Conversation;
pub use super::conversation_message::Entity as ConversationMessage;
pub use super::participant::Entity as Participant;
pub use super::user::Entity as User;
